spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tasksdb
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  runner:
    mode: local
